### ISSUE TITLE
ClusterInstallError using cfy_cluster_manager 

### ISSUE THREAD

**Issue by Steeew47** [cloudify-cosmo/cloudify-cluster-manager#50]
The `ClusterInstallError` prevents the correct installation of the cloudify cluster using `cfy_cluster_manager install` command.

#### For all cluster nodes:
* Operating System: CentOS Linux 7 (Core)
* Virtualization: vmware

## Log:
```
[root@localhost cloudify]#  cfy_cluster_manager install --override
[CFY-CLUSTER-MANAGER] - INFO - Installing a Cloudify cluster
[CFY-CLUSTER-MANAGER] - INFO - Validating node-1
[CFY-CLUSTER-MANAGER] - INFO - Validating node-2
[CFY-CLUSTER-MANAGER] - INFO - Validating node-3
[CFY-CLUSTER-MANAGER] - INFO - Checking for a previous installation
[CFY-CLUSTER-MANAGER] - INFO - Cloudify cluster was previously installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if postgresql-1 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if postgresql-2 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if postgresql-3 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if rabbitmq-1 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if rabbitmq-2 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if rabbitmq-3 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if manager-1 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if manager-2 was installed
[CFY-CLUSTER-MANAGER] - INFO - Checking if manager-3 was installed
[CFY-CLUSTER-MANAGER] - INFO - Preparing cluster mangaer files
[CFY-CLUSTER-MANAGER] - INFO - Creating `cloudify_cluster_manager` directory
[CFY-CLUSTER-MANAGER] - INFO - Cloudify RPM is already installed
[CFY-CLUSTER-MANAGER] - INFO - Generating certificates
[CFY-CLUSTER-MANAGER] - INFO - Preparing PostgreSQL config files
[CFY-CLUSTER-MANAGER] - INFO - Preparing RabbitMQ config files
[CFY-CLUSTER-MANAGER] - INFO - Preparing Manager config files
[CFY-CLUSTER-MANAGER] - INFO - installing postgresql instances
[CFY-CLUSTER-MANAGER] - INFO - Installing postgresql-1
[CFY-CLUSTER-MANAGER] - INFO - Copying the /tmp/cloudify_cluster_manager directory to postgresql-1
[CFY-CLUSTER-MANAGER] - ERROR - ClusterInstallError: The command `cp /tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml /etc/cloudify/postgresql-1_config.yaml` on host 192.168.248.133 failed with the error cp: cannot stat ‘/tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml’: No such file or directory
```

## Detailed error log using `--verbose` option
```
[CFY-CLUSTER-MANAGER] - INFO - Copying the /tmp/cloudify_cluster_manager directory to postgresql-1
[CFY-CLUSTER-MANAGER] - DEBUG - Copying /tmp/cloudify_cluster_manager to /tmp/cloudify_cluster_manager on host 192.168.248.133
[CFY-CLUSTER-MANAGER] - DEBUG - Running `rm -rf /tmp/cloudify_cluster_manager` on 192.168.248.133
[CFY-CLUSTER-MANAGER] - DEBUG - Checking if Cloudify RPM was installed on 192.168.248.133
[CFY-CLUSTER-MANAGER] - DEBUG - Running `rpm -qi cloudify-manager-install` on 192.168.248.133
[CFY-CLUSTER-MANAGER] - DEBUG - Running `cp /tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml /etc/cloudify/postgresql-1_config.yaml` on 192.168.248.133
[CFY-CLUSTER-MANAGER] - ERROR - ClusterInstallError: The command `cp /tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml /etc/cloudify/postgresql-1_config.yaml` on host 192.168.248.133 failed with the error cp: cannot stat ‘/tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml’: No such file or directory

[CFY-CLUSTER-MANAGER] - DEBUG - Traceback (most recent call last):
  File "/bin/cfy_cluster_manager", line 33, in <module>
    sys.exit(load_entry_point('cloudify-cluster-manager==1.0.2', 'console_scripts', 'cfy_cluster_manager')())
  File "/opt/cfy_cluster_manager/lib64/python3.6/site-packages/cfy_cluster_manager/main.py", line 1071, in main
    install(args.config_path, args.override, args.validate, args.verbose)
  File "/opt/cfy_cluster_manager/lib64/python3.6/site-packages/cfy_cluster_manager/main.py", line 939, in install
    rpm_download_link, verbose)
  File "/opt/cfy_cluster_manager/lib64/python3.6/site-packages/cfy_cluster_manager/main.py", line 378, in _install_instances
    instance.config_path), use_sudo=True)
  File "/opt/cfy_cluster_manager/lib64/python3.6/site-packages/cfy_cluster_manager/utils.py", line 139, in run_command
    '{2}'.format(command, self.private_ip, result.stderr))
cfy_cluster_manager.utils.ClusterInstallError: The command `cp /tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml /etc/cloudify/postgresql-1_config.yaml` on host 192.168.248.133 failed with the error cp: cannot stat ‘/tmp/cloudify_cluster_manager/config_files/postgresql-1_config.yaml’: No such file or directory
```

## The configuration file used during the installation
```
# Your private SSH key local path used to connect to all VMs
ssh_key_path: '/root/.ssh/id_rsa'

# The VMs' SSH username, e.g. centos
ssh_user: 'root'

# Local path to a valid Cloudify license
cloudify_license_path: '/etc/cloudify/LICENSE'

# Manager RPM to install on the cluster instances
manager_rpm_download_link: 'http://repository.cloudifysource.org/cloudify/5.1.0/ga-release/cloudify-manager-install-5.1.0ga.rpm'

# This section is only relevant if using LDAP
ldap:
  # This should include the protocol and port,
  # e.g. ldap://192.0.2.1:389 or ldaps://192.0.2.45:636
  server: ''

  # The domain, e.g. example.local
  domain: ''

  # True if Active Directory will be used as the LDAP authenticator
  is_active_directory: true

  # This must be provided if the server is using ldaps://
  ca_cert: ''

  # Username and password should only be entered if absolutely required
  # by the ldap service.
  username: ''
  password: ''

  # Any extra LDAP information (separated by the `;` sign. e.g. a=1;b=2)
  dn_extra: ''


# If specified, all the VMs' certificates will need to be specified as well
ca_cert_path: ''

# If using a load-balancer, please provide its IP.
# This IP will be written to the manager config.yaml files under
# networks[load_balancer].
# Remark: The load balancer is not installed during the cluster installation.
load_balancer_ip: '192.168.248.137'


existing_vms:
    node-1:
      private_ip: '192.168.248.133'
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: 'node1'   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      # Optional. In case you wish to use your own config.yaml files.
      config_path:
        manager_config_path: ''
        postgresql_config_path: ''
        rabbitmq_config_path: ''

    node-2:
      private_ip: '192.168.248.131'
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: 'node2'   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      # Optional. In case you wish to use your own config.yaml files.
      config_path:
        manager_config_path: ''
        postgresql_config_path: ''
        rabbitmq_config_path: ''

    node-3:
      private_ip: '192.168.248.134'
      public_ip: ''  # If not specified, will default to the private-ip
      hostname: 'node3'   # Optional. As specified in the certificate (if specified)
      cert_path: ''  # Need to be supplied if ca_cert_path was supplied
      key_path: ''  # Need to be supplied if ca_cert_path was supplied
      # Optional. In case you wish to use your own config.yaml files.
      config_path:
        manager_config_path: ''
        postgresql_config_path: ''
        rabbitmq_config_path: ''


# If the credentials are not specified, random self-generated ones will be used and written to /home/node1/secret_credentials.yaml
credentials:
  manager:
    admin_username: ''
    admin_password: ''

  postgresql:
    postgres_password: ''
    cluster:
      etcd:
        cluster_token: ''
        root_password: ''
        patroni_password: ''
      patroni:
        rest_password: ''
      postgres:
        replicator_password: ''

  rabbitmq:
    username: ''
    password: ''
    erlang_cookie: ''

  prometheus:
    username: ''
    password: ''

```

**Comment by YoniItzhak** [comment]
Hi, thank you for raising this issue, it was solved in v1.0.4.
